# Generated by Django 3.2.7 on 2021-09-27 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Log',
            new_name='AccountUser',
        ),
    ]
